export const JS_SANDBOX_WORKER_SOURCE = [
  '"use strict";',
  '',
  'const normalizeOutput = (value) => {',
  '  return String(value ?? "")',
  '    .replace(/\\r\\n/g, "\\n")',
  '    .replace(/\\s+$/g, "")',
  '    .trim();',
  '};',
  '',
  'const formatValue = (val) => {',
  '  const type = typeof val;',
  '  if (val === null || val === undefined) return String(val);',
  '  if (type === "object") {',
  '    try {',
  '      return JSON.stringify(val);',
  '    } catch (err) {',
  '      return "[object]";',
  '    }',
  '  }',
  '  return String(val);',
  '};',
  '',
  'const disableDangerousAPIs = () => {',
  '  const blocked = [',
  '    "fetch",',
  '    "XMLHttpRequest",',
  '    "WebSocket",',
  '    "navigator",',
  '    "document",',
  '    "window",',
  '    "parent",',
  '    "localStorage",',
  '    "sessionStorage",',
  '    "caches",',
  '    "indexedDB",',
  '    "FileReader",',
  '    "File",',
  '  ];',
  '  blocked.forEach((key) => {',
  '    try {',
  '      self[key] = undefined;',
  '    } catch (err) {',
  '      // ignore',
  '    }',
  '  });',
  '};',
  '',
  'disableDangerousAPIs();',
  '',
  'self.onmessage = (event) => {',
  '  const payload = event.data || {};',
  '  if (payload.type !== "run") return;',
  '',
  '  const { code = "", testCases = [], timeLimitMs = 2000 } = payload;',
  '  const logs = [];',
  '  const errors = [];',
  '  const results = [];',
  '',
  '  const consoleProxy = {',
  '    log: (...args) => logs.push(args.map(formatValue).join(" ")),',
  '    warn: (...args) => logs.push("[warn] " + args.map(formatValue).join(" ")),',
  '    error: (...args) => logs.push("[error] " + args.map(formatValue).join(" ")),',
  '  };',
  '',
  '  const runUserCode = (inputText) => {',
  '    const inputLines = String(inputText ?? "").split("\\n");',
  '    const readInput = () => (inputLines.length ? inputLines.shift() : "");',
  '    // Provide a minimal prompt shim for browser-style solutions',
  '    const promptShim = () => readInput();',
  '    const userFn = new Function("readInput", "console", "prompt", code);',
  '    return userFn(readInput, consoleProxy, promptShim);',
  '  };',
  '',
  '  const guard = setTimeout(() => {',
  '    self.postMessage({ type: "timeout", logs, errors: ["Time Limit Exceeded"] });',
  '    try {',
  '      self.close();',
  '    } catch (err) {',
  '      // ignore',
  '    }',
  '  }, timeLimitMs);',
  '',
  '  try {',
  '    testCases.forEach((tc, index) => {',
  '      const startIdx = logs.length;',
  '      try {',
  '        runUserCode(tc.input);',
  '      } catch (err) {',
  '        const message = err && err.message ? err.message : String(err);',
  '        errors.push("Test " + (index + 1) + ": " + message);',
  '        results.push({',
  '          pass: false,',
  '          output: "",',
  '          expected: tc?.expected || "",',
  '          error: message,',
  '        });',
  '        return;',
  '      }',
  '',
  '      const outputSegment = logs.slice(startIdx).join("\\n");',
  '      const expected = tc?.expected || "";',
  '      const pass = normalizeOutput(outputSegment) === normalizeOutput(expected);',
  '',
  '      results.push({',
  '        pass,',
  '        output: outputSegment,',
  '        expected,',
  '        error: null,',
  '      });',
  '    });',
  '  } catch (err) {',
  '    const message = err && err.message ? err.message : String(err);',
  '    errors.push(message);',
  '  }',
  '',
  '  clearTimeout(guard);',
  '  self.postMessage({ type: "result", logs, errors, results });',
  '  try {',
  '    self.close();',
  '  } catch (err) {',
  '    // ignore',
  '  }',
  '};',
].join('\n');
